config/routes.rb
Planswithfriends::Application.routes.draw do

  get "home/trigger"

  resources :socialize_plans do
    collection do
      get 'create_plan'
    end
  end

  root :to => "home#index"

end

app/models/socialize_plan.rb
require 'rubygems'
require 'httparty'
require 'json'
class SocializePlan < ActiveRecord::Base
  
  def self.get_access_token
    consumer_key = 'a297dac5-f39e-4f2b-a2d7-c94f6e1f2bcc'
    consumer_secret = '5f72e9cb-33e4-4245-b80e-a0d63905670b'
    
    access_key_token = 'c396b52b-f94b-425f-8338-8072a8bd5f0d'
    access_key_secret = '3c70a37f-969b-4014-ad1b-e30f4bd29ff6'
    base_url = "http://api.getsocialize.com"
    
    consumer = OAuth::Consumer.new(consumer_key, consumer_secret , :site => "http://api.getsocialize.com")
    access_token = OAuth::AccessToken.new(consumer, access_key_token, access_key_secret)
  end
  
  def self.process_activity(entity_identifier)
    context_path = "/v1/comment/?entity_key="
    
    # options = {:query => {:entity_key => activity_identifier, :output => "json"}, headers=>{:oauth_consumer_key=>'',}}
    #     source_events = HTTParty.get(base_url+context_path, options)
    access_token = get_access_token
    
    response = access_token.get(context_path+entity_identifier)
    puts response.body
    json_response = JSON.parse(response.body)
    return if json_response['items'].size == 0
    sorted_response = json_response['items'].sort{|x,y| y['date'].to_date <=> x['date'].to_date}
    item = sorted_response[0]
    i = 0 ; 
    while i<sorted_response.size && !sorted_response[i]['text'].starts_with?('planswithfriends') do
      item = sorted_response[i]
      puts item
      parts = item['text'].split(' ')
      if parts.size == 2 && (parts[0].upcase == 'WEATHER' || parts[0].upcase == 'MOVIES')
        topic = parts[0]
        location = parts[1]
        puts "topic: #{topic}, location: #{location}"
        comment = get_info(topic,location)
        puts "comment: #{comment}"
        access_token.post('/v1/comment/',{ :payload=>"[{\"entity_key\":\""+entity_identifier+"\",\"text\":\""+comment+"\"}]"})
      end
      i = i+1
    end
  end
  
  def self.get_info(topic, loc)
    weather_bug_url = "http://i.wxbug.net/REST/Direct/GetForecast.ashx?zip="+loc+"&nf=3&c=US&l=en&api_key=fxyashp63d8494p288c8na4n"
    rotten_tomatoes_url = "http://api.rottentomatoes.com/api/public/v1.0/lists/movies/box_office.json?limit=5&country=us&apikey=e73t27rtwd89jjvcpk5h7het"
    if topic.upcase == 'WEATHER'
      json_data = HTTParty.get(weather_bug_url)
      #puts json_data
      comment = "planswithfriends- Day Prediction-"+JSON.parse(json_data.body)['forecastList'][0]['dayPred']+". Night Prediction-"+JSON.parse(json_data.body)['forecastList'][0]['nightPred']
    elsif topic.upcase == 'MOVIES'
      json_data = HTTParty.get(rotten_tomatoes_url)
      comment = "planswithfriends-"+json_data['movies'].collect{|x| x['title']}.join(', ')
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def trigger
    @socialize_plans = SocializePlan.all
    @socialize_plans.each{|s| SocializePlan.process_activity(s.identifier)}
  end

end

app/controllers/socialize_plans_controller.rb
class SocializePlansController < ApplicationController
  # GET /socialize_plans
  # GET /socialize_plans.xml
  def index
    @socialize_plans = SocializePlan.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @socialize_plans }
      format.json  { render :json => @socialize_plans }
    end
  end

  # GET /socialize_plans/1
  # GET /socialize_plans/1.xml
  def show
    @socialize_plan = SocializePlan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @socialize_plan }
      format.json  { render :json => @socialize_plan }
    end
  end

  # GET /socialize_plans/new
  # GET /socialize_plans/new.xml
  def new
    @socialize_plan = SocializePlan.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @socialize_plan }
    end
  end

  # GET /socialize_plans/1/edit
  def edit
    @socialize_plan = SocializePlan.find(params[:id])
  end

  # POST /socialize_plans
  # POST /socialize_plans.xml
  def create
    @socialize_plan = SocializePlan.new(params[:socialize_plan])

    respond_to do |format|
      if @socialize_plan.save
        format.html { redirect_to(@socialize_plan, :notice => 'Socialize plan was successfully created.') }
        format.xml  { render :xml => @socialize_plan, :status => :created, :location => @socialize_plan }
        format.json  { render :json => @socialize_plans }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @socialize_plan.errors, :status => :unprocessable_entity }
        format.json  { render :json => @socialize_plan.errors,  :status => :unprocessable_entity}
      end
    end
  end

  # GET /socialize_plans/create_plan?name=XYZ&identifier=XYZ
  def create_plan
    @socialize_plan = SocializePlan.new(:name=>params[:name], :identifier=>params[:identifier])
    respond_to do |format|
      if @socialize_plan.save
        @socialize_plans = SocializePlan.all
        @socialize_plans.each{|s| SocializePlan.process_activity(s.identifier)}
        render :json => @socialize_plans
      else
        @socialize_plans = SocializePlan.all
        @socialize_plans.each{|s| SocializePlan.process_activity(s.identifier)}
        render :json => @socialize_plan.errors,  :status => :unprocessable_entity
      end
    end
  end

  # PUT /socialize_plans/1
  # PUT /socialize_plans/1.xml
  def update
    @socialize_plan = SocializePlan.find(params[:id])

    respond_to do |format|
      if @socialize_plan.update_attributes(params[:socialize_plan])
        format.html { redirect_to(@socialize_plan, :notice => 'Socialize plan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @socialize_plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /socialize_plans/1
  # DELETE /socialize_plans/1.xml
  def destroy
    @socialize_plan = SocializePlan.find(params[:id])
    @socialize_plan.destroy

    respond_to do |format|
      format.html { redirect_to(socialize_plans_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/socialize_plans_helper.rb
module SocializePlansHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/trigger.html.erb
<h1>Home#trigger</h1>
<p>Done</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planswithfriends</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/socialize_plans/_form.html.erb
<%= form_for(@socialize_plan) do |f| %>
  <% if @socialize_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@socialize_plan.errors.count, "error") %> prohibited this socialize_plan from being saved:</h2>

      <ul>
      <% @socialize_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/socialize_plans/edit.html.erb
<h1>Editing socialize_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @socialize_plan %> |
<%= link_to 'Back', socialize_plans_path %>

app/views/socialize_plans/index.html.erb
<h1>Listing socialize_plans</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Identifier</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @socialize_plans.each do |socialize_plan| %>
  <tr>
    <td><%= socialize_plan.name %></td>
    <td><%= socialize_plan.identifier %></td>
    <td><%= link_to 'Show', socialize_plan %></td>
    <td><%= link_to 'Edit', edit_socialize_plan_path(socialize_plan) %></td>
    <td><%= link_to 'Destroy', socialize_plan, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Socialize plan', new_socialize_plan_path %>

app/views/socialize_plans/new.html.erb
<h1>New socialize_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', socialize_plans_path %>

app/views/socialize_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @socialize_plan.name %>
</p>

<p>
  <b>Identifier:</b>
  <%= @socialize_plan.identifier %>
</p>


<%= link_to 'Edit', edit_socialize_plan_path(@socialize_plan) %> |
<%= link_to 'Back', socialize_plans_path %>